title:             SNJ Group
email:             tresnajati2.com
description:       Papan Pasinaon Aksara Jawa
author:            Wong Turian
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://pasinaon.jawa.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   Wongturian
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate